为Dockerfile中添加替换alpine镜像源命令
解决神奇的网络问题
Step 8/14 : RUN apk --no-cache add ca-certificates
 ---> Running in a525d7759627
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
ERROR: unable to select packages:
  ca-certificates (no such package):
    required by: world[ca-certificates]
The command '/bin/sh -c apk --no-cache add ca-certificates' returned a non-zero code: 1